"""connections

Revision ID: 0ff2e67ea526
Revises: 67630c85e1ad
Create Date: 2025-01-01 16:54:42.808744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff2e67ea526'
down_revision = '67630c85e1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_achievement', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('achievement_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('teacher_hobby', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hobby_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teacher_hobby', schema=None) as batch_op:
        batch_op.alter_column('hobby_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teacher_achievement', schema=None) as batch_op:
        batch_op.alter_column('achievement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
