"""empty message

Revision ID: 1263bed46417
Revises: 96cc897e1629
Create Date: 2025-01-19 21:14:26.393843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1263bed46417'
down_revision = '96cc897e1629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.String(), nullable=True))
        batch_op.drop_column('free_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_text', sa.TEXT(), nullable=True))
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
