"""edit search

Revision ID: 2b85f068cfb5
Revises: 0ff2e67ea526
Create Date: 2025-01-08 17:36:22.937558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b85f068cfb5'
down_revision = '0ff2e67ea526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
