"""empty message

Revision ID: 347983ee4839
Revises: 752abded3dc7
Create Date: 2025-01-14 21:37:03.139918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347983ee4839'
down_revision = '752abded3dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_free', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('is_free')

    # ### end Alembic commands ###
