"""profiles

Revision ID: 613f538176df
Revises: 4f3b42a9754c
Create Date: 2025-02-07 21:03:00.818481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613f538176df'
down_revision = '4f3b42a9754c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('teacher_id', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
