"""school

Revision ID: 67630c85e1ad
Revises: e426f5e0d53a
Create Date: 2025-01-01 14:43:41.304135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67630c85e1ad'
down_revision = 'e426f5e0d53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('school',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('school',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
