"""crm

Revision ID: 752abded3dc7
Revises: 2b85f068cfb5
Create Date: 2025-01-10 21:37:59.470241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752abded3dc7'
down_revision = '2b85f068cfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    # ### end Alembic commands ###
