"""empty message

Revision ID: 8438dff8422a
Revises: 8fab51b0b3fc
Create Date: 2025-02-16 21:32:14.454602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8438dff8422a'
down_revision = '8fab51b0b3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
