"""study_paths_new_version

Revision ID: 84fbdd4bc76e
Revises: 867b3d90117b
Create Date: 2025-08-31 18:23:41.153253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fbdd4bc76e'
down_revision = '867b3d90117b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_school', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_oge', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_olymps', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('is_olymps')
        batch_op.drop_column('is_oge')
        batch_op.drop_column('is_school')

    # ### end Alembic commands ###
