"""stydy path

Revision ID: 867b3d90117b
Revises: d435605213ac
Create Date: 2025-08-12 19:23:03.713510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867b3d90117b'
down_revision = 'd435605213ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_path', sa.Enum('all', 'oge', 'olymps', 'school', name='studypath'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('study_path')

    # ### end Alembic commands ###
