"""positons

Revision ID: 932bc89cde57
Revises: a5fdfd33ce2e
Create Date: 2025-02-16 19:00:40.442005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932bc89cde57'
down_revision = 'a5fdfd33ce2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
