"""parent replies

Revision ID: d435605213ac
Revises: 3616dee21594
Create Date: 2025-07-23 19:56:55.869476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd435605213ac'
down_revision = '3616dee21594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('bottom_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_reply')
    # ### end Alembic commands ###
