"""tariff

Revision ID: e426f5e0d53a
Revises: e063d0e82faa
Create Date: 2025-01-01 14:12:13.930730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e426f5e0d53a'
down_revision = 'e063d0e82faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_teacher_tariff'), ['tariff'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_tariff'))
        batch_op.drop_column('tariff')

    # ### end Alembic commands ###
