"""oge balls

Revision ID: e6f61398d91b
Revises: 84fbdd4bc76e
Create Date: 2025-09-21 19:37:38.214643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f61398d91b'
down_revision = '84fbdd4bc76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oge_ball', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('oge_ball')

    # ### end Alembic commands ###
